name: CMake C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests (if any)
      run: ctest --test-dir build
